POST http://127.0.0.1:5000/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "non@no",
  "password": "dog"
}
###

POST http://127.0.0.1:5000/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "non@no",
  "password": "dog"
}

###
PUT http://127.0.0.1:5000/auth/login
Accept: application/json
Content-Type: application/json

{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vQCIsImV4cCI6MTY1OTAwMzEwNX0.F2fa1fZUcK4LjdKhcmA0EBKf2hmBB9xZ29Gz2j3hO2U",
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vQCIsImV4cCI6MTY3MDIzNDIwNX0.SmqUnxv-HIkiLWI1fPzXOX78wbxd0f2BWv06T9-dROg"
}

###
GET http://127.0.0.1:5000/user
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTgxNzU0MH0.ZMe5ZFDlbYsHmGo87WdokysiPlk3RMOT9jC9-B5urmw




###
PATCH http://127.0.0.1:5000/user/
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTgxNzU0MH0.ZMe5ZFDlbYsHmGo87WdokysiPlk3RMOT9jC9-B5urmw

{"name": "Фекла"}

###
PUT http://127.0.0.1:5000/user/password
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTAwNjkwOX0.UtxC_wwuPuln1DRXt_tMc07lrX5jnQQaLN8sSQuZMpk

{
   "password_1": "pony",
   "password_2": "dog"
}

###
POST http://127.0.0.1:5000/favourites/movies/18
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTgxNzU0MH0.ZMe5ZFDlbYsHmGo87WdokysiPlk3RMOT9jC9-B5urmw


###

DELETE http://127.0.0.1:5000/favourites/movies/10
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTgxNzU0MH0.ZMe5ZFDlbYsHmGo87WdokysiPlk3RMOT9jC9-B5urmw


###
