POST http://127.0.0.1:5000/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "non@no",
  "password": "dog"
}

###
POST http://127.0.0.1:5000/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "non@no",
  "password": "dog"
}

###
PUT http://127.0.0.1:5000/auth/login
Accept: application/json
Content-Type: application/json

{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTgyMjM2NX0._75KnekiQppoV1yWEkxLY6Y7t3begFjWmvSC3rttOr0",
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY3MTA1MzQ2NX0.uj4aQonKIVOsfVj40vMQKD2bmPxrL_6mOHsx6i7JASs"
}

###
GET http://127.0.0.1:5000/user
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTgyMzU4MX0.AJmeD1Kwd7jsuLTb9H-J5C4e0LwrweKxle8s5XiSa4c




###
PATCH http://127.0.0.1:5000/user/
Accept: application/json
Content-Type: application/json
Authorization: yJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTgyMTE1OH0.RD9uz6R7xgqnLRTnR0jWwkIV4dhNLY9lsfu_voi_iWM

{"name": "Фекла"}

###
PUT http://127.0.0.1:5000/user/password
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTAwNjkwOX0.UtxC_wwuPuln1DRXt_tMc07lrX5jnQQaLN8sSQuZMpk

{
   "password_1": "pony",
   "password_2": "dog"
}

###
POST http://127.0.0.1:5000/favourites/movies/20
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTgyMzU4MX0.AJmeD1Kwd7jsuLTb9H-J5C4e0LwrweKxle8s5XiSa4c


###

DELETE http://127.0.0.1:5000/favourites/movies/1
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vbkBubyIsImV4cCI6MTY1OTgyMzU4MX0.AJmeD1Kwd7jsuLTb9H-J5C4e0LwrweKxle8s5XiSa4c

###
